# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Update toolchains
dist: xenial

addons:
  apt:
    packages:
    - gcc
    - g++
    - clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make